modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/RaphiMC/ImmediatelyFast/issues"
license = "LGPL-3.0"

[[mods]]
modId = "immediatelyfast"
version = "${version}"
displayName = "ImmediatelyFast"
authors = "RK_01"
description = '''
Speed up and optimize immediate mode rendering in Minecraft
'''
logoFile = "immediatelyfast-icon.png"

[[mixins]]
config = "immediatelyfast-neoforge.mixins.json"
[[mixins]]
config = "immediatelyfast-common.mixins.json"

[[dependencies.immediatelyfast]]
modId = "neoforge"
required = true
versionRange = "[20.5.0-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.immediatelyfast]]
modId = "minecraft"
required = true
versionRange = "[1.20.5]"
ordering = "NONE"
side = "CLIENT"
